name: AWS SSM Send-Command Action
description: Run command on the EC2 instance through SSM

inputs:
  aws-access-key-id:
    description: AWS_ACCESS_KEY_ID
    required: true
  aws-secret-access-key:
    description: AWS_SECRET_ACCESS_KEY
    required: true
  aws-region:
    description: AWS_REGION
    required: true
  targets:
    description: Target Instances
    required: true
  document-name:
    description: Document Name
    default: AWS-RunShellScript
    required: false
  parameters:
    description: Parameters depend on document
    required: true
  timeout:
    description: Timeout to command
    default: '60'
    required: false

outputs:
  status:
    description: Status

runs:
  using: node12
  main: dist/index.js

branding:
  icon: chevron-up
  color: green